/** @fileoverview 从真实 PostgreSQL Schema 生成兼容既有调用方命名的 Kysely 类型。 */

const { TypeScriptSerializer } = require('kysely-codegen');

const SINGULAR_TABLE_RULES = {
  '/^attachments$/i': 'attachment_table',
  '/^documentrevisions$/i': 'document_revision_table',
  '/^documents$/i': 'document_table',
  '/^idempotencyrecords$/i': 'idempotency_record_table',
  '/^inboxitems$/i': 'inbox_item_table',
  '/^knowledgebases$/i': 'knowledge_base_table',
  '/^outboxevents$/i': 'outbox_event_table',
  '/^searchblocks$/i': 'search_block_table',
  '/^searchdocumentprojections$/i': 'search_document_projection_table',
  '/^users$/i': 'user_table',
};
const baseSerializer = new TypeScriptSerializer({
  singularize: SINGULAR_TABLE_RULES,
  skipAutogeneratedFileComment: true,
});

/** 用于在生成结果末尾保留现有数据库边界使用的稳定类型名。 */
function serializeDatabaseTypes(metadata, dialect, options) {
  const generated = baseSerializer
    .serializeFile(metadata, dialect, options)
    .replace(
      'import type { ColumnType } from "kysely";',
      'import type { ColumnType } from "kysely" with { "resolution-mode": "import" };',
    )
    .replace(
      'export type JsonObject = {\n  [x: string]: JsonValue | undefined;\n};',
      'export interface JsonObject {\n  [x: string]: JsonValue | undefined;\n}',
    );
  return `/** @fileoverview 此文件由 kysely-codegen 从真实 PostgreSQL Schema 生成，禁止手工编辑。 */\n\n${generated}\nexport type DatabaseSchema = DB;\n`;
}

module.exports = {
  defaultSchemas: ['public'],
  dialect: 'postgres',
  includePattern: 'public.*',
  logLevel: 'warn',
  outFile: './src/database/database.types.ts',
  overrides: {
    columns: {
      'attachments.kind': "'file' | 'image'",
      'attachments.status': "'active' | 'pending'",
      'document_revisions.source': "'ai' | 'automation' | 'import' | 'manual' | 'restore'",
      'inbox_items.kind': "'text' | 'url'",
      'inbox_items.status': "'converted' | 'pending'",
      'knowledge_bases.kind': "'news' | 'normal' | 'tutorial'",
      'outbox_events.event_type': "'document.deleted' | 'document.restored' | 'document.saved'",
    },
  },
  serializer: { serializeFile: serializeDatabaseTypes },
};
